### PR TITLE
Exercise:10

### PR DESCRIPTION
**Pull request by lashd**
This is a first crack at #10. @joshnesbitt could you give this a look?

### CODE REVIEW

**Comment by joshnesbitt** [comment]
Do we want to be careful merging the solution @lashd? Will take a proper look at this when I get a chance.

**Comment by lashd** [comment]
I don't think that I have merged any solution code? Definitely a mistake if I have.

**Comment by joshnesbitt** [comment]
@lashd sorry you haven't merged it yet, but this PR contains a solution that's going to get merged into master right?

**Comment by lashd** [comment]
@joshnesbitt don't think there is any solution code in there. If you are reffering to the specs? I originally added those because I thought that they could run code coverage and add the missing tests. I then replaced code coverage for rubocop and but left them in because there was warning thrown by rubocop that I wanted them to switch off. 

We could take these out and do something dedicated to wiring in coverage?

**Comment by joshnesbitt** [comment]
@lashd ah OK I see what you're doing. Should be fine then. Sorry not able to dedicate proper time on this now but will review properly soon.

**Comment by lashd** [comment]
We could add a part b) to the first exercise, getting them to customise the rspec tasks and turn on code coverage then add this missing test? (the missing tests are checking that exceptions are thrown)

e.g.

```
RSpec::Core::RakeTask.new(:spec) do
  ENV['coverage'] = true
end
```

Then in the spec help they could check for this environment variable to require the necessary simplecov bits and pieces?

**Comment by lashd** [comment]
@joshnesbitt no problem - when ever you get the time.

**Pull request merged**
